_BASE_: Base-cnn.yml

MODEL:
  BACKBONE:
    DEPTH: "50x"
    FEAT_DIM: 2048
    WITH_IBN: False
    PRETRAIN: True
    PRETRAIN_PATH: /home/helingxiao3/.cache/torch/checkpoints/resnet50_ibn_a-d9d0bb7b.pth


OUTPUT_DIR: projects/Basic_Project/basemodel/r50
